// Power Query Calendar v1.0
//Created By: Jon Lunn jonhenrylunn@gmail.com
//www.jlsql.wordpress.com

let
	// Can set you start date range here
	Source = List.Dates,
	#"Invoked FunctionSource" = Source(#date(2015, 1, 1), Duration.Days(#date(Date.Year(DateTime.FixedLocalNow()), 12, 31) - #date(2015,1,1)), #duration(1, 0, 0, 0)),
	#"Table from List" = Table.FromList(#"Invoked FunctionSource", Splitter.SplitByNothing(), null, null, ExtraValues.Error),
	#"Added Index" = Table.AddIndexColumn(#"Table from List", "CalendarKey", 1, 1),
	#"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Column1", "Date"}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"CalendarKey", "Date"}),
	// All below items are dependant on the [Date] Column
	// Remove the ones you don't need
    // Day
	#"Add Short Day Name" = Table.AddColumn(#"Reordered Columns", "DayShortName", each Date.ToText([Date],"ddd")),
    #"Add Day Long Name" = Table.AddColumn(#"Add Short Day Name", "DayLongName", each Date.ToText([Date],"dddd")),
    #"Add Day Of Week" = Table.AddColumn(#"Add Day Long Name", "DayOfWeek", each Date.DayOfWeek([Date])),
    #"Add Is Week Day" = Table.AddColumn(#"Add Day Of Week", "IsWeekday", each if Date.DayOfWeek([Date]) >= 5 then 0 else 1),
	// Month
    #"Add Month Key" = Table.AddColumn(#"Add Is Week Day", "MonthKey", each Date.Month([Date])),
    #"Add Month Short Name" = Table.AddColumn(#"Add Month Key", "MonthShortName", each Date.ToText([Date],"MMM")),
	#"Add Month Long Name" = Table.AddColumn(#"Add Month Short Name", "MonthLongName", each Date.ToText([Date],"MMMM")),
    #"Add Month Year Name" = Table.AddColumn(#"Add Month Long Name", "MonthYearName", each Date.ToText([Date], "MMM") & "-" & Date.ToText([Date], "yy")),
    #"Add Month Year Key" = Table.AddColumn(#"Add Month Year Name", "MonthYearKey", each Number.FromText(Number.ToText(Date.Year([Date])) & Number.ToText(Date.Month([Date]), "00"))),
	// Quarter
	#"Add Quarter Of Year" = Table.AddColumn(#"Add Month Year Key", "QuarterOfYear", each Date.QuarterOfYear([Date])),
    #"Add Quarter Name" = Table.AddColumn(#"Add Quarter Of Year", "QuarterName", each "Q" & Number.ToText(Date.QuarterOfYear([Date]), "00")),
    #"Add Quarter Year Name" = Table.AddColumn(#"Add Quarter Name", "QuarterYearName", each "Q" & Number.ToText(Date.QuarterOfYear([Date]), "00") & "-" & Date.ToText([Date], "yy")),
    #"Add Quarter Year Key" = Table.AddColumn(#"Add Quarter Year Name", "QuarterYearKey", each Number.FromText(Number.ToText(Date.Year([Date])) & Number.ToText(Date.QuarterOfYear([Date]), "00"))),
	// Year
    #"Add Year Column" = Table.AddColumn(#"Add Quarter Year Key", "Year", each Date.Year([Date])),
    #"Added Week Key" = Table.AddColumn(#"Add Year Column", "WeekKey", each Date.WeekOfYear([Date])),
    #"Added Week Name" = Table.AddColumn(#"Added Week Key", "WeekName", each "WK" & Number.ToText(Date.WeekOfYear([Date]), "00")),
    #"Added Week Year Key" = Table.AddColumn(#"Added Week Name", "Week Year Key", each Number.FromText(Number.ToText(Date.Year([Date])) & Number.ToText(Date.WeekOfYear([Date]), "00"))),
    #"Added Week Year Name" = Table.AddColumn(#"Added Week Year Key", "Week Year Name", each "WK" & Number.ToText(Date.WeekOfYear([Date]), "00") & "-" &  Date.ToText([Date], "yy")),
    #"Added Current Day" = Table.AddColumn(#"Added Week Year Name", "Current Day", each Date.IsInCurrentDay([Date])),
    #"Added Days Ago" = Table.AddColumn(#"Added Current Day", "Days Ago", each Duration.Days([Date] - DateTime.Date(DateTime.FixedLocalNow()))),
    #"Added Months Ago" = Table.AddColumn(#"Added Days Ago", "Months Ago", each ((Date.Year([Date])-Date.Year(DateTime.LocalNow()))*12) + Date.Month([Date]) - Date.Month(DateTime.LocalNow())),
    #"Added Quarters Ago" = Table.AddColumn(#"Added Months Ago", "Quarters Ago", each Date.QuarterOfYear([Date]) - Date.QuarterOfYear(DateTime.LocalNow()) + ((Date.Year(DateTime.Date([Date]))-Date.Year(DateTime.LocalNow())) * 4)),
    #"Added Years Ago" = Table.AddColumn(#"Added Quarters Ago", "Years Ago", each Date.Year(DateTime.Date([Date]))-Date.Year(DateTime.LocalNow())),
    #"Added Current Week" = Table.AddColumn(#"Added Years Ago", "Current Week", each Date.IsInCurrentWeek([Date])),
    #"Added Current Month" = Table.AddColumn(#"Added Current Week", "Current Month", each Date.IsInCurrentMonth([Date])),
    #"Added Current Quarter" = Table.AddColumn(#"Added Current Month", "Current Quarter", each Date.IsInCurrentQuarter([Date])),
    #"Added Current Year" = Table.AddColumn(#"Added Current Quarter", "Current Year", each Date.IsInCurrentYear([Date])),
    #"Changed Type" = Table.TransformColumnTypes(#"Added Current Year",{{"Date", type date}})
in
    #"Changed Type"
